export const DEFAULT_MEMBERSHIP_PRODUCTS = [
  {
    code: 'membership-7d',
    title: '体验周',
    subtitle: '先体验扩展报告与海报权益',
    description: '适合先体验扩展报告、海报生成与记录管理入口。',
    priceFen: 1900,
    durationDays: 7,
    benefitsJson: ['扩展报告', '海报生成', '记录管理'],
    sortOrder: 10,
    status: 'published',
  },
  {
    code: 'membership-30d',
    title: '月度权益',
    subtitle: '扩展内容的标准方案',
    description: '适合持续查看性格、情绪和阶段性记录的扩展解读。',
    priceFen: 3900,
    durationDays: 30,
    benefitsJson: ['扩展报告', '海报生成', '历史记录管理'],
    sortOrder: 20,
    status: 'published',
  },
  {
    code: 'membership-90d',
    title: '季度权益',
    subtitle: '适合长期内容体验与分享',
    description: '适合需要持续查看阶段性变化和反复生成分享海报的用户。',
    priceFen: 9900,
    durationDays: 90,
    benefitsJson: ['扩展报告', '海报生成', '历史记录管理', '优先体验新能力'],
    sortOrder: 30,
    status: 'published',
  },
] as const;
