import type { FortuneContentEntity } from '../database/entities/fortune-content.entity';

type SeedContent = Pick<
  FortuneContentEntity,
  'contentType' | 'bizCode' | 'title' | 'summary' | 'contentJson' | 'status' | 'publishDate'
>;

export const LUCKY_SIGN_SEEDS: SeedContent[] = [
  {
    contentType: 'lucky_sign',
    bizCode: 'sign-breeze-open',
    title: '今日幸运签',
    summary: '先把心绪放松一点，再做决定，顺势比硬顶更容易得到答案。',
    publishDate: null,
    status: 'published',
    contentJson: {
      tag: '风起有信',
      interpretation: '今天适合先打开信息流和感受力，答案会在不那么用力的时候出现。',
      mantra: '先松一口气，再向前一步。',
      favorableWindow: '10:00 - 13:00',
      goodFor: '适合沟通、确认安排、做一次轻量整理。',
      avoid: '不要在疲惫和上头的时候做情绪化决定。',
      suggestions: [
        '先完成一件最小但明确的任务，让节奏重新流动。',
        '给重要沟通留一点缓冲和回看空间。',
        '今天更适合柔和推进，而不是一次性冲到底。',
      ],
      accent: 'mint',
    },
  },
  {
    contentType: 'lucky_sign',
    bizCode: 'sign-still-water',
    title: '今日幸运签',
    summary: '把注意力收回来，先稳住自己，很多杂音会自然退下去。',
    publishDate: null,
    status: 'published',
    contentJson: {
      tag: '静水见明',
      interpretation: '今天的好运来自稳定感。先照顾节奏，再处理变化，会更容易保持判断力。',
      mantra: '慢一点，也是在往前。',
      favorableWindow: '14:00 - 18:00',
      goodFor: '适合复盘、预算梳理、身体放松、处理细节。',
      avoid: '不要让外部节奏把你带进连续内耗。',
      suggestions: [
        '把待办重新排一次优先级，先处理最耗能的那一项。',
        '和信任的人确认一次边界，会让今天更轻松。',
        '留一点空白时间给自己，后面的效率会更高。',
      ],
      accent: 'blue',
    },
  },
  {
    contentType: 'lucky_sign',
    bizCode: 'sign-soft-glow',
    title: '今日幸运签',
    summary: '把温柔和明确放在一起，你会比平时更容易吸引到好的回应。',
    publishDate: null,
    status: 'published',
    contentJson: {
      tag: '柔光成事',
      interpretation: '今天适合带着一点温度去表达自己，越真诚，越容易碰到顺势的协同。',
      mantra: '表达清楚，温柔也有力量。',
      favorableWindow: '19:00 - 22:00',
      goodFor: '适合社交、表达、分享、发出邀请。',
      avoid: '不要因为怕打扰而把真正重要的话吞回去。',
      suggestions: [
        '把今天最想推进的一件事说出来，别人更容易接住你。',
        '一条真诚但简洁的信息，会比反复犹豫更有效。',
        '如果状态不错，可以记录一句今天的幸运感受。',
      ],
      accent: 'peach',
    },
  },
];

export const LUCKY_ITEM_SEEDS: SeedContent[] = [
  {
    contentType: 'lucky_item',
    bizCode: 'item-mint-notebook',
    title: '薄荷色随记本',
    summary: '适合把今天的灵感、待办和小决定收拢起来。',
    publishDate: null,
    status: 'published',
    contentJson: {
      category: '随身物',
      elements: ['木', '水'],
      zodiacs: ['双子座', '天秤座', '双鱼座', '巨蟹座'],
      useMoment: '上午启动和下午整理时',
      styleHint: '选择浅薄荷或雾蓝封面，会让状态更轻盈。',
      recommendationReason: '它适合把发散的信息重新收束，让今天更有秩序感。',
      palette: ['#d7f0e6', '#edf8f6', '#9ccdb7'],
      wallpaperPrompt: 'misty mint notebook, soft daylight, calm desktop mood',
    },
  },
  {
    contentType: 'lucky_item',
    bizCode: 'item-metal-pen',
    title: '银白金属笔',
    summary: '适合需要做决定、签字、整理重点的日子。',
    publishDate: null,
    status: 'published',
    contentJson: {
      category: '办公物',
      elements: ['金', '水'],
      zodiacs: ['处女座', '摩羯座', '水瓶座'],
      useMoment: '会议前、整理方案时',
      styleHint: '哑光银或冰川灰更适合今天的冷静判断。',
      recommendationReason: '它会强化清晰度和边界感，适合把重要事项说清楚。',
      palette: ['#dfe5ec', '#f7f9fb', '#a9b7c6'],
      wallpaperPrompt: 'minimal silver pen, cool light, clean modern desk',
    },
  },
  {
    contentType: 'lucky_item',
    bizCode: 'item-amber-cup',
    title: '暖杏色水杯',
    summary: '适合提醒自己放慢节奏、补充能量与耐心。',
    publishDate: null,
    status: 'published',
    contentJson: {
      category: '日常物',
      elements: ['土', '火'],
      zodiacs: ['金牛座', '狮子座', '射手座'],
      useMoment: '午后疲惫或需要安定情绪时',
      styleHint: '暖杏、淡茶色会让今天的状态更柔和。',
      recommendationReason: '它更像一个“慢下来”的提示器，帮你把能量留给真正重要的事。',
      palette: ['#f4d9b8', '#fff4ea', '#d8b184'],
      wallpaperPrompt: 'amber ceramic cup, warm afternoon light, airy lifestyle shot',
    },
  },
  {
    contentType: 'lucky_item',
    bizCode: 'item-crystal-tray',
    title: '透光小托盘',
    summary: '适合整理桌面、放钥匙首饰，也适合当成今天的视觉锚点。',
    publishDate: null,
    status: 'published',
    contentJson: {
      category: '空间物',
      elements: ['金', '土'],
      zodiacs: ['处女座', '天秤座', '摩羯座'],
      useMoment: '收纳小物、整理环境时',
      styleHint: '透明或珍珠白更适合今天的秩序感。',
      recommendationReason: '当环境被整理好时，你会更容易进入稳定而不急躁的节奏。',
      palette: ['#f2f5f8', '#ffffff', '#c9d5de'],
      wallpaperPrompt: 'clear crystal tray, pearly white palette, serene room aesthetic',
    },
  },
  {
    contentType: 'lucky_item',
    bizCode: 'item-ocean-scarf',
    title: '海盐蓝丝巾',
    summary: '适合今天增加一点流动感和表达感。',
    publishDate: null,
    status: 'published',
    contentJson: {
      category: '穿搭物',
      elements: ['水', '木'],
      zodiacs: ['双鱼座', '巨蟹座', '天秤座'],
      useMoment: '社交、约会、轻松表达时',
      styleHint: '海盐蓝、雾青色会提升今天的轻盈感。',
      recommendationReason: '它会让你的表达更柔和，适合靠近、联结和分享。',
      palette: ['#d5e7ef', '#f5fbff', '#89adc1'],
      wallpaperPrompt: 'soft ocean blue silk scarf, airy fashion flat lay, clean apple style',
    },
  },
  {
    contentType: 'lucky_item',
    bizCode: 'item-forest-perfume',
    title: '清林木质香',
    summary: '适合需要重新找回专注力和边界感的时候。',
    publishDate: null,
    status: 'published',
    contentJson: {
      category: '气味物',
      elements: ['木', '土'],
      zodiacs: ['白羊座', '处女座', '摩羯座'],
      useMoment: '进入工作流或独处整理时',
      styleHint: '偏木质、微冷感的香气更适合今天。',
      recommendationReason: '它会提醒你把注意力拉回自己，适合稳住节奏再推进。',
      palette: ['#dde8dc', '#f7faf6', '#9aae97'],
      wallpaperPrompt: 'forest perfume bottle, soft green tones, minimal still life',
    },
  },
];
