import { Injectable } from '@nestjs/common';
import { UserEntity } from '../database/entities/user.entity';

@Injectable()
export class ExploreService {
  getExploreIndex(user: UserEntity | null) {
    const isProfileCompleted = Boolean(user?.birthday && user?.zodiac);

    return {
      code: 0,
      message: 'ok',
      data: {
        isLoggedIn: Boolean(user),
        searchPlaceholder: '搜索测试 / 冥想 / 星座 / 八字',
        todayFit: {
          icon: '莲',
          text: isProfileCompleted ? '今日适合：情绪疗愈' : '今日适合：完善资料后再深入探索',
          route: isProfileCompleted ? '/pages/emotion/index' : '/pages/profile/index',
        },
        filters: {
          types: [
            { label: '全部', value: 'all' },
            { label: '心理测试', value: 'test' },
            { label: '冥想', value: 'meditation' },
            { label: '星座', value: 'zodiac' },
            { label: '八字', value: 'bazi' },
            { label: '日记', value: 'journal' },
            { label: '内容', value: 'content' },
          ],
          goals: [
            { label: '放松', value: 'relax' },
            { label: '睡眠', value: 'sleep' },
            { label: '减压', value: 'stress' },
            { label: '自我探索', value: 'self' },
            { label: '关系分析', value: 'relationship' },
          ],
        },
        banner: {
          eyebrow: '为你推荐',
          title: '情绪自测与疗愈地图',
          summary: '识别情绪状态，找到专属疗愈方案。',
          ctaText: '立即探索',
          icon: '莲',
          route: '/pages/emotion/index',
        },
        features: [
          {
            id: 'emotion',
            title: '心理测试',
            description: '心情评分 / 抑郁倾向 / 焦虑状态',
            icon: '心',
            type: 'test',
            goals: ['stress', 'self'],
            route: '/pages/emotion/index',
          },
          {
            id: 'zodiac',
            title: '星座运势',
            description: '今日运势 / 星座解析',
            icon: '月',
            type: 'zodiac',
            goals: ['self'],
            route: '/pages/zodiac/index',
          },
          {
            id: 'bazi',
            title: '八字命理',
            description: '五行 / 流日气运',
            icon: '卦',
            type: 'bazi',
            goals: ['self'],
            route: '/pages/bazi/index',
          },
          {
            id: 'meditation',
            title: '冥想放松',
            description: '呼吸 / 睡眠 / 减压',
            icon: '静',
            type: 'meditation',
            goals: ['relax', 'sleep', 'stress'],
            route: '/pages/emotion/index',
          },
          {
            id: 'journal',
            title: '情绪日记',
            description: '记录心情 / 情绪追踪',
            icon: '记',
            type: 'journal',
            goals: ['self', 'stress'],
            route: '/pages/records/index',
          },
          {
            id: 'compatibility',
            title: '合盘合性',
            description: '关系分析 / 默契度',
            icon: '合',
            type: 'content',
            goals: ['relationship'],
            route: '/pages/zodiac/index',
          },
          {
            id: 'healing',
            title: '疗愈内容',
            description: '文章 / 音频 / 卡片',
            icon: '泉',
            type: 'content',
            goals: ['relax', 'stress'],
            route: '/pages/lucky/index',
          },
          {
            id: 'more',
            title: '更多工具',
            description: '塔罗灵感 / 自我觉察',
            icon: '罗',
            type: 'content',
            goals: ['self'],
            route: '/pages/lucky/index',
          },
        ],
        topics: [
          {
            id: 'stress',
            title: '焦虑缓解',
            summary: '舒缓压力，找回平静',
            tag: '热门',
            route: '/pages/emotion/index',
          },
          {
            id: 'sleep',
            title: '睡前疗愈',
            summary: '放松身心，安稳入眠',
            tag: '睡眠',
            route: '/pages/emotion/index',
          },
          {
            id: 'week',
            title: '本周星缘',
            summary: '把握星象能量',
            tag: '星座',
            route: '/pages/zodiac/index',
          },
        ],
        contents: [
          {
            id: 'reset',
            title: '3 分钟情绪复位练习',
            description: '快速平复情绪，回到内心的稳定中心。',
            icon: '水',
            type: '冥想',
            filterType: 'meditation',
            goals: ['relax', 'stress'],
            duration: '8 分钟',
            stat: '1.2 万人练习',
            buttonText: '进入',
            route: '/pages/emotion/index',
          },
          {
            id: 'zodiac-week',
            title: '本周星座能量提醒',
            description: '本周星象影响解析，提前掌握重要转折。',
            icon: '星',
            type: '星座',
            filterType: 'zodiac',
            goals: ['self'],
            duration: '5 分钟阅读',
            stat: '2.3 万人关注',
            buttonText: '查看',
            route: '/pages/zodiac/index',
          },
          {
            id: 'element',
            title: '今日五行平衡建议',
            description: '结合八字五行，看今日能量如何调和。',
            icon: '衡',
            type: '八字',
            filterType: 'bazi',
            goals: ['self'],
            duration: '6 分钟阅读',
            stat: '9861 人查看',
            buttonText: '查看',
            route: '/pages/bazi/index',
          },
        ],
      },
      timestamp: new Date().toISOString(),
    };
  }
}
